import { expect, test, type Route } from '@playwright/test';
import { assertWorkspaceTestLock } from '@/lib/testing/workspace-test-lock';

test('customer live refresh preserves page scope, retained rows and failure recovery without route refresh', async ({ page }) => {
  assertWorkspaceTestLock();
  const bundle = process.env.WERKFLOW_UI_CONTRACT_BUNDLE;
  if (!bundle) throw new Error('Run through the UI contract runner');
  const requests: Route[] = [];
  const requestAt = (index: number): Route => {
    const route = requests[index];
    if (!route) throw new Error(`expected customer page request ${index + 1}`);
    return route;
  };
  await page.route('**/api/customer-page?*', route => { requests.push(route); });
  await page.clock.install({ time: new Date('2026-09-12T10:00:00Z') });
  await page.clock.pauseAt(new Date('2026-09-12T10:00:01Z'));
  const url = 'http://localhost/ui-contracts';
  await page.route(url, route => route.fulfill({ contentType: 'text/html', body: '<html lang="de"><body><div id="root"></div></body></html>' }));
  await page.goto(url);
  await page.evaluate(() => { window.uiContractFixture = 'customer'; });
  await page.addScriptTag({ path: bundle });
  await expect(page.getByRole('table', { includeHidden: true }).getByText('Ausgangsstand', { exact: true }).filter({ visible: true })).toBeVisible();
  expect(requests).toHaveLength(0);
  await page.evaluate(() => window.calendarContract.emit('clients'));
  await page.clock.runFor(151);
  await expect.poll(() => requests.length).toBe(1);
  const query = new URL(requestAt(0).request().url()).searchParams;
  expect(query.get('page')).toBe('2'); expect(query.get('search')).toBe('Kontakt');
  await requestAt(0).fulfill({ status: 500, json: { error: 'read_failed' } });
  await expect(page.getByRole('status').filter({ hasText: 'Die Kundenliste konnte nicht aktualisiert werden. Bitte versuche es erneut.' })).toBeVisible();
  await expect(page.getByRole('table', { includeHidden: true }).getByText('Ausgangsstand', { exact: true }).filter({ visible: true })).toBeVisible();
  await page.getByRole('button', { name: 'Tabelle aktualisieren' }).click();
  await expect.poll(() => requests.length).toBe(2);
  const row = { id: '10000000-0000-4000-8000-000000000003', organizationId: '10000000-0000-4000-8000-000000000001', name: 'Aktueller Stand', clientType: 'privat', customerNumber: null, email: null, phone: null, address: null, notes: null, createdAt: '', updatedAt: '' };
  await requestAt(1).fulfill({ json: { clients: [row], total: 62 } });
  await expect(page.getByRole('table', { includeHidden: true }).getByText('Aktueller Stand', { exact: true }).filter({ visible: true })).toBeVisible();
  await expect(page.getByRole('status').filter({ hasText: 'Die Kundenliste konnte nicht aktualisiert werden. Bitte versuche es erneut.' })).toHaveCount(0);
  await page.getByRole('button', { name: 'Serverantwort liefern' }).click();
  await expect.poll(() => requests.length).toBe(3);
  await expect(page.getByRole('table', { includeHidden: true }).getByText('Alter Serverstand', { exact: true })).toHaveCount(0);
  await requestAt(2).fulfill({ json: { clients: [{ ...row, name: 'Bestätigter neuer Stand' }], total: 62 } });
  await expect(page.getByRole('table', { includeHidden: true }).getByText('Bestätigter neuer Stand', { exact: true }).filter({ visible: true })).toBeVisible();
  await page.getByRole('button', { name: 'Entwurf einfügen', exact: true }).click();
  await expect(page.getByRole('table', { includeHidden: true }).getByText('Außerhalb der Seite', { exact: true }).filter({ visible: true })).toBeVisible();
  await page.getByRole('button', { name: 'Speichern bestätigen' }).click();
  await expect.poll(() => requests.length).toBe(4);
  await requestAt(3).fulfill({ status: 500, json: { error: 'read_failed' } });
  await expect(page.getByRole('status').filter({ hasText: 'Die Kundenliste konnte nicht aktualisiert werden. Bitte versuche es erneut.' })).toBeVisible();
  await expect(page.getByRole('table', { includeHidden: true }).getByText('Außerhalb der Seite', { exact: true }).filter({ visible: true })).toBeVisible();
  await page.getByRole('button', { name: 'Weiteren Entwurf einfügen' }).click();
  await page.getByRole('button', { name: 'Tabelle aktualisieren' }).click();
  await expect.poll(() => requests.length).toBe(5);
  await requestAt(4).fulfill({ json: { clients: [row], total: 62 } });
  await expect(page.getByRole('table', { includeHidden: true }).getByText('Außerhalb der Seite', { exact: true })).toHaveCount(0);
  await expect(page.getByRole('table', { includeHidden: true }).getByText('Noch nicht gespeichert', { exact: true }).filter({ visible: true })).toBeVisible();
  await page.getByRole('button', { name: 'Speichern bestätigen' }).click();
  await expect.poll(() => requests.length).toBe(6);
  await page.getByRole('button', { name: 'Weiteren Entwurf einfügen' }).click();
  await page.getByRole('button', { name: 'Fehlgeschlagenen Entwurf entfernen' }).click();
  await expect.poll(() => requests.length).toBe(7);
  await requestAt(6).fulfill({ json: { clients: [row], total: 62 } });
  await expect(page.getByRole('table', { includeHidden: true }).getByText('Außerhalb der Seite', { exact: true })).toHaveCount(0);
  await expect(page.getByRole('table', { includeHidden: true }).getByText('Noch nicht gespeichert', { exact: true })).toHaveCount(0);
  expect(await page.evaluate(() => window.uiContractServices.navigation)).toEqual([]);
  await page.getByRole('button', { name: 'Alte Organisationsantwort liefern' }).click();
  await expect(page.getByRole('table', { includeHidden: true }).getByText('Fremder Kunde', { exact: true })).toHaveCount(0);
  expect(requests).toHaveLength(7);
  await page.evaluate(() => window.calendarContract.emit('clients'));
  await page.clock.runFor(151);
  await expect.poll(() => requests.length).toBe(8);
  await page.evaluate(() => { window.calendarContract.emit('clients'); window.calendarContract.emit('client_contacts'); });
  await page.clock.runFor(500);
  expect(requests).toHaveLength(8);
  await requestAt(7).fulfill({ json: { clients: [{ ...row, name: 'Erste Antwort' }], total: 62 } });
  await expect(page.getByRole('table', { includeHidden: true }).getByText('Erste Antwort', { exact: true })).toBeVisible();
  await page.clock.runFor(151);
  await expect.poll(() => requests.length).toBe(9);
  await requestAt(8).fulfill({ json: { clients: [{ ...row, name: 'Nach allen Ereignissen' }], total: 62 } });
  await expect(page.getByRole('table', { includeHidden: true }).getByText('Nach allen Ereignissen', { exact: true })).toBeVisible();
  await page.clock.runFor(1_100);
  expect(requests).toHaveLength(9);
});
