-- Restore explicit historical row and sequence privileges for clean installations.
-- Older migrations relied on Supabase default grants. This finite inventory matches
-- the existing DEV/local privileges; it does not grant access to future objects or
-- change RLS policies. Anonymous SQL privileges still require a permitting RLS policy.

grant select, update, usage on sequence
  public.time_segment_events_event_sequence_seq
to anon;

grant delete, insert, select, update on table
  public.attention_events,
  public.attention_read_states,
  public.client_communication_preference_events,
  public.client_communication_preferences,
  public.client_communication_settings,
  public.client_contacts,
  public.client_follow_up_events,
  public.client_follow_ups,
  public.client_request_events,
  public.client_requests,
  public.client_sites,
  public.clients,
  public.document_audit_events,
  public.document_folders,
  public.document_links,
  public.document_versions,
  public.documents,
  public.employee_record_events,
  public.employee_records,
  public.employment_conditions,
  public.entry_change_requests,
  public.installed_equipment,
  public.installed_equipment_event_links,
  public.installed_equipment_events,
  public.installed_equipment_identifiers,
  public.installed_equipment_work_links,
  public.inventory_asset_instances,
  public.inventory_categories,
  public.inventory_import_batches,
  public.inventory_item_barcodes,
  public.inventory_items,
  public.inventory_locations,
  public.inventory_stock_levels,
  public.inventory_suppliers,
  public.job_assignments,
  public.job_instruction_items,
  public.job_material_lines,
  public.jobs,
  public.organization_closure_days,
  public.organization_invites,
  public.organization_members,
  public.organization_settings,
  public.organization_user_preferences,
  public.organizations,
  public.planning_customer_commitment_events,
  public.planning_customer_commitments,
  public.planning_dispatch_acknowledgements,
  public.planning_dispatch_events,
  public.planning_dispatch_recipients,
  public.planning_dispatch_revisions,
  public.planning_dispatches,
  public.profiles,
  public.projects,
  public.service_case_equipment_links,
  public.service_case_events,
  public.service_case_evidence_links,
  public.service_case_relations,
  public.service_cases,
  public.sickness_report_events,
  public.sickness_reports,
  public.subscriptions,
  public.time_entries,
  public.vacation_request_events,
  public.vacation_requests,
  public.work_handover_draft_items,
  public.work_handover_events,
  public.work_handover_packages,
  public.work_handover_release_items,
  public.work_handover_releases,
  public.work_schedules
to anon;

grant insert, select on table
  public.inventory_audit_events,
  public.inventory_movements
to anon;

grant select, update, usage on sequence
  public.time_segment_events_event_sequence_seq
to authenticated;

grant delete, insert, select, update on table
  public.attention_events,
  public.attention_read_states,
  public.client_contacts,
  public.client_request_events,
  public.client_requests,
  public.client_sites,
  public.clients,
  public.document_audit_events,
  public.document_folders,
  public.document_links,
  public.document_versions,
  public.documents,
  public.employee_record_events,
  public.employee_records,
  public.employment_conditions,
  public.entry_change_requests,
  public.job_assignments,
  public.job_instruction_items,
  public.jobs,
  public.organization_closure_days,
  public.organization_invites,
  public.organization_members,
  public.organization_settings,
  public.organization_user_preferences,
  public.organizations,
  public.planning_customer_commitment_events,
  public.planning_customer_commitments,
  public.planning_dispatch_acknowledgements,
  public.planning_dispatch_events,
  public.planning_dispatch_recipients,
  public.planning_dispatch_revisions,
  public.planning_dispatches,
  public.profiles,
  public.projects,
  public.sickness_report_events,
  public.sickness_reports,
  public.subscriptions,
  public.time_entries,
  public.vacation_request_events,
  public.vacation_requests,
  public.work_handover_draft_items,
  public.work_handover_events,
  public.work_handover_packages,
  public.work_handover_release_items,
  public.work_handover_releases,
  public.work_schedules
to authenticated;

grant delete, insert, update on table
  public.client_communication_preference_events,
  public.client_communication_preferences,
  public.client_communication_settings,
  public.client_follow_up_events,
  public.client_follow_ups,
  public.installed_equipment,
  public.installed_equipment_event_links,
  public.installed_equipment_events,
  public.installed_equipment_identifiers,
  public.installed_equipment_work_links,
  public.service_case_equipment_links,
  public.service_case_events,
  public.service_case_evidence_links,
  public.service_case_relations,
  public.service_cases
to authenticated;

grant select, update, usage on sequence
  public.time_segment_events_event_sequence_seq
to service_role;

grant delete, insert, select, update on table
  public.attention_events,
  public.attention_read_states,
  public.client_contacts,
  public.client_request_events,
  public.client_requests,
  public.client_sites,
  public.clients,
  public.document_audit_events,
  public.document_folders,
  public.document_links,
  public.document_versions,
  public.documents,
  public.email_change_challenges,
  public.employee_record_events,
  public.employee_records,
  public.employment_conditions,
  public.entry_change_requests,
  public.job_assignments,
  public.job_instruction_items,
  public.jobs,
  public.organization_closure_days,
  public.organization_invites,
  public.organization_members,
  public.organization_settings,
  public.organization_user_preferences,
  public.organizations,
  public.planning_customer_commitment_events,
  public.planning_customer_commitments,
  public.planning_dispatch_acknowledgements,
  public.planning_dispatch_events,
  public.planning_dispatch_recipients,
  public.planning_dispatch_revisions,
  public.planning_dispatches,
  public.profiles,
  public.projects,
  public.sickness_report_events,
  public.sickness_reports,
  public.subscriptions,
  public.time_correction_applications,
  public.time_correction_events,
  public.time_correction_request_revisions,
  public.time_correction_request_sources,
  public.time_correction_requests,
  public.time_entries,
  public.time_operations,
  public.time_segment_events,
  public.time_segments,
  public.time_sessions,
  public.vacation_request_events,
  public.vacation_requests,
  public.work_handover_draft_items,
  public.work_handover_events,
  public.work_handover_packages,
  public.work_handover_release_items,
  public.work_handover_releases,
  public.work_schedules
to service_role;

grant delete, insert, update on table
  public.ordinary_documents
to service_role;

